yolo_model:

  config_file:
    name: tiny_dice1256.cfg
  weight_file:
    name: tiny_dice1256_20000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - dice5
      - dice6
      - dice1
      - dice2
