# File containing task definitions.

# INITIALIZE.
initialize:
  actions:
    - initialize:
        countdown: 10
        drift_check: 3

# GATE TASK
# The gate is a purely dead reckoning task.
gate:
  actions: []

# BUOY TASK
buoy:
  actions: []

# MANEUVER TASK
# Maneuver with feedback. Might want to do something fancy at the end for
# style points!
maneuver:
  actions: []

# BINS TASK
# Drop marker in bins.
bins:
  actions: []

# TORPEDO TASK
# Move to torpedos and then shoot.
torpedo:
  actions: []

# OCTAGON TASK
# Search for octogon using hydrophones.
octagon:
  actions: []

# TEST TASK
# Represents any series of actions for testing purposes.
square:
  actions:
    - move_all:
        yaw: 0.0
        distance: 1.5
        depth: 0.0
#FOLLOW LANE
#Finds a Lane, servos to center and turns
follow_lane:
  actions:
    - follow_lane: "not needed"

#ROULETTE TASK
#Looks for roulette and servos to the center
roulette:
  actions:
    - roulette: "not needed"

dice:
  actions:
    - dice_servo:
        diceName: 'dice6'
    - move:
        distance: 1.5
    - move:
        distance: -1.5
    - dice_servo:
        diceName: 'dice5'
    - move:
        distance: 1.5

