#File containing parameters for the different tasks

move_all:
  max_stable_counts: 15
  yaw_threshold: 0.15
  depth_threshold: 0.2

dive:
  stablePeriods: 50


lanes:
  foundCounts: 10
  centerStableCounts: 30
  centerMaxError: 0.4
  turnStableCount: 30
  turnMaxError: 0.1


roulette:
  foundCounts: 30
  centerStableCounts: 100
  centerMaxError: 0.4

dice:
  foundCounts: 100
  centerStableCounts: 50
  centerMaxError: 0.4

vacuum:
  suckDuration: 100
  suckingPower: 400