# File containing task definitions.

# INITIALIZE.
initialize:
  actions:
    - initialize:
        countdown: 10
        drift_check: 3

# GATE TASK
# The gate is a purely dead reckoning task.
gate:
  actions:
    - move_all:
        depth: 1.2
        yaw: 0.0
        distance: 21.0

# BUOY TASK
buoy:
  actions:
    - move_all:
        yaw: 0.035
        distance: 14.0
        depth: 1.2

# MANEUVER TASK
# Maneuver with feedback. Might want to do something fancy at the end for
# style points!
maneuver:
  actions:
    - move_all:
        yaw: 0.47
        distance: 11.0
        depth: 1.2
    - move_all:
        yaw: 0.65
        depth: 1.2

# BINS TASK
# Drop marker in bins.
bins:
  actions:
    - acoustic_servo:
        - depth: 1.2
    - move_all:
        distance: -0.1
        depth: 1.2
    - bins_servo:
        - depth: 1.2
        - yaw: 0.65
    - shoot: starboard_dropper
    - shoot: port_dropper

# TORPEDO TASK
# Move to torpedos and then shoot.
torpedo:
  actions:
    - turn:
        angle: 0.1
    - visual_servo_front: torpedo
    - shoot: starboard_torpedo
    - shoot: port_torpedo

# OCTAGON TASK
# Search for octogon using hydrophones.
octagon:
  actions:
    - acoustic_servo:
        depth: 1.2
    - move_all:
        distance: -0.1
        depth: 1.2
    - move_all:
        depth: 0.0

# TEST TASK
# Represents any series of actions for testing purposes.
square:
  actions:
    - acoustic_servo:
        depth: 0.6
