# INITIALIZE.
initialize:
  actions:
    - initialize:
        countdown: 5
        drift_check: 2

# GATE TASK
# The gate is a purely dead reckoning task.
gate:
  actions:
    - move:
        distance: 10  # 13.8
        depth: 1.2
        yaw: 0.0

# BUOY TASK
buoy:
  actions:
    - move:  # Move close to the buoys
        distance: 9.5  # 5.87
        depth: 1.7
        yaw: 0.0
    - move:
        distance: 1
    - move:
        distance: 2.8
        depth: 1.2
        yaw: 0.698

# MANEUVER TASK
# Maneuver with feedback. Might want to do something fancy at the end for
# style points!
maneuver:
  actions:
    - move: # move to maneuver
        distance: 3.5
        depth: 1.9
        yaw: -0.35
    - spinny: spin!
    - spinny: spin!!
    - move: # go through
        distance: 21
        depth: 1.9
        yaw: -1.047
    - move: # last turn
        distance: 0
        depth: 1.2
        yaw: -2.27

# OCTAGON TASK
# Search for octogon using hydrophones.
octagon:
  actions:
    - move:
        distance: 0
        depth: 1.2
    - acoustic_servo: "hydrophones"
    - move:
        distance: -0.6
    - move:
        distance: 0
        depth: 0.1

# BINS TASK
# Drop marker in bins.
bins:
  actions:
    - move:
        distance: 0
        depth: 1.2
    - acoustic_servo: "hydrophones"
    - move:
        distance: -1.0
        depth: 1.2
    - shoot: port_dropper
    - move:
        distance: 0.8
        depth: 1.2
    - shoot: starboard_dropper

# TORPEDO TASK
# Move to torpedos and then shoot.
torpedo:
  actions:
    - move:
        distance: 0
        depth: 1.7
        yaw: 1.4
    - shoot: port_torpedo
    - move:
        distance: 0
        depth: 1.3
        yaw: 1.3
    - shoot: starboard_torpedo
    -

# TEST TASK
# Represents any series of actions for testing purposes.
square:
  actions:
    - move:
        distance: -2
        depth: 1.2
        sway: True
