tasks:
  - name:  INITIALIZE  # name of the state
    server: initialize_task  # name of the action server
  - name: CONDITIONAL
    server: hydro_choose_task
    results:
      right_tasks:
        - name: OCTAGON
          server: octagon_task
        - name: BIN
          server: bin_task
      left_tasks:
        - name: BIN
          server: bin_task
        - name: OCTAGON
          server: octagon_task
    transitions:
      left: left_tasks
      right: right_tasks
