tasks:
  - name: SQUARE
    server: square_task
  - name: CONDITIONAL
    server: hydro_choose_task
    results:
      left_tasks:
        - name: SQUARE
          server: square_task
      right_tasks:
        - name: GATE
          server: gate_task
    transitions:
      left: left_tasks
      right: right_tasks
