tasks:
  - name:  INITIALIZE  # name of the state
    server: initialize_task  # name of the action server
  - name: SQUARE
    server: square_task
  - name: WAIT
    server: wait
  - name: SQUARE
    server: square_task
