initialize: [3,0]
move1: {time:[1,0], velocity:[0,0,0,0,0,0], theta: 0.0, depth: 0}
move2: {time:[5,0], velocity:[10,0,4,0,0,0], theta: 0, depth: 0}
move3: {time:[5,0], velocity:[10,0,4,0,0,0], theta: 1.57, depth: 0}
move4: {time:[5,0], velocity:[10,0,4,0,0,0], theta: 3.14, depth: 0}
