initialize: [10,0]
move1: {time:[1,0], velocity:[1,0,0,0,0,0], theta: 0.0, depth: 10.0}
move2: {time:[0,0], velocity:[0,0,0,0,0,0], theta: 0.00, depth: 10.0}
move3: {time:[0,0], velocity:[0,0,0,0,0,0], theta: 0.00, depth: 10.0}
move4: {time:[0,0], velocity:[0,0,0,0,0,0], theta: 0.00, depth: 10.0}
