# File containing task definitions.

# INITIALIZE.
initialize:
  actions:
    - initialize:
        countdown: 10
        drift_check: 3

# GATE TASK
# The gate is a purely dead reckoning task.
gate:
  actions:
    - move_all:
        depth: 1.5
        yaw: 0.0
        distance: 35.0

# BUOY TASK
buoy:
  actions:
    - move_all:
        yaw: -0.53
        distance: 20.0
        depth: 1.5

# MANEUVER TASK
# Maneuver with feedback. Might want to do something fancy at the end for
# style points!
maneuver:
  actions:
    - move_all:
        yaw: -0.56
        distance: 25.0
        depth: 1.5
    - move_all:
        yaw: -0.87
        depth: 1.5

# BINS TASK
# Drop marker in bins.
bins:
  actions:
    - acoustic_servo:
        depth: 1.5
    - move_all:
        distance: -0.3
        depth: 1.5
    - bins_servo:
        depth: 1.5
        yaw: -0.87
    - shoot: starboard_dropper
    - shoot: port_dropper

# TORPEDO TASK
# Move to torpedos and then shoot.
torpedo:
  actions:
    - turn:
        angle: 0.1
    - visual_servo_front: torpedo
    - shoot: starboard_torpedo
    - shoot: port_torpedo

# OCTAGON TASK
# Search for octogon using hydrophones.
octagon:
  actions:
    - acoustic_servo:
        depth: 1.5
    - move_all:
        distance: -0.3
        depth: 1.5

# TEST TASK
# Represents any series of actions for testing purposes.
square:
  actions:
    - move_all:
        depth: 1.5
        yaw: 3.14
        distance: 0.0
