# Lists represent the K_p, K_i, K_d gains respectively
translation_gains: {
    surge: [20.0, 0.0, 0.0],
    sway: [50.0, 0.0, 0.0],
    heave: [150.0, 4.0, 10]
}
rotation_gains: {
    pitch: [5.0, 0.0, 0.0],
    roll: [1.0, 0.0, 0.0],
    yaw: [20.0, 0.0, 5.0]
}
