# Lists represent the K_p, K_i, K_d gains respectively
translation_gains:
    surge: [0.15, 0.0, 0.50]
    sway: [0.15, 0.0, 0.50]
    heave: [50.0, 5.0, 20.0]

rotation_gains:
    pitch: [0.15, 0.0, 0.50]
    roll: [0.15, 0.0, 0.50]
    yaw: [1.5, 0.5, 3.0]
