# Lists represent the K_p, K_i, K_d gains respectively
translation_gains:
    surge: [10.0, 0.0, 0.0]
    sway: [10.0, 0.0, 0.0]
    heave: [10.0, 0.0, 0.0]

rotation_gains:
    pitch: [5.0, 0.0, 0.0]
    roll: [1.0, 0.0, 0.0]
    yaw: [2.0, 0.0, 1.0]
