#!/usr/bin/env python

# Quick fix that subscribes to /cmd_vel
# and publishes to controls/wrench

import rospy
import geometry_msgs.msg


def joystick():
    global wrench_msg
    wrench_msg = geometry_msgs.msg.Wrench()

    rospy.init_node('joystick')

    pub = rospy.Publisher('/controls/wrench', 
            geometry_msgs.msg.Wrench, queue_size=1)

    sub = rospy.Subscriber('/cmd_vel', 
            geometry_msgs.msg.Twist, callback_function, queue_size = 1)

    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rospy.loginfo(wrench_msg)
        pub.publish(wrench_msg)
        rate.sleep()
    rospy.spin()


def callback_function(twist_msg):
    wrench_msg.force = twist_msg.linear
    wrench_msg.torque = twist_msg.angular


if __name__ == '__main__':
    joystick()
