# ~/.tmuxinator/auv.yml

name: MAIN
root: /home/robotics/auv

pre: mv ~/.zhistory ~/.zhistory.old && strings ~/.zhistory.old > ~/.zhistory && export SHELL=/bin/zsh && export PATH=/usr/local/sbin/:/usr/local/bin/:/usr/sbin:${PATH}:/sbin:/usr/games:/usr/local/games

windows:
    - core: roscore
    - serial: roslaunch arduino arduino.launch --wait
    - cameras:
        panes:
          - roslaunch cv camera_front_1.launch --wait
          - roslaunch cv camera_front_2.launch --wait
          - roslaunch cv camera_down.launch --wait
    - sonar:
        panes:
          - roslaunch tritech_micron tritech_micron.launch --wait
          - roslaunch sonar_proc sonar_proc.launch --wait
    - state_estimation: roslaunch state_estimation state_estimation.launch --wait
    - controls: roslaunch controls controls.launch --wait
    - status:
        panes:
          - roslaunch status status.launch --wait --screen
          - roslaunch dcdc_nuc dcdc_nuc.launch --wait
    - planner: roslaunch planner planner.launch --wait
    - taskr: roslaunch taskr taskr.launch --wait
    - hydrophones: roslaunch hydrophones hydrophones.launch --wait
    - auto_shutdown: rosrun status auto_shutdown
    - bag: /home/robotics/record.sh
    - gui:
        - roslaunch gui gui.launch --wait
    - gui2:
         - rosrun rospy_tutorials add_two_ints_server --wait
